### ISSUE TITLE
README needs updating.

### ISSUE THREAD

**Issue by ivanhawkes** [philsquared/Clara#34]
Composing args with + symbols causes errors on compilation. Those should probably be | symbols instead.

**Comment by MKlimenko** [comment]
There are two pull requests addressing this issue: [one](https://github.com/philsquared/Clara/pull/33) and [two](https://github.com/philsquared/Clara/pull/35).

**Comment by philsquared** [comment]
Yep - sorry about that - just getting back on top of this.
