### ISSUE TITLE
Support slashes as option separators, at least under Windows

### ISSUE THREAD

**Issue by vadz** [philsquared/Clara#9]
It's pretty common to use slashes instead of dashes under Windows and most other command line parsing libraries support this. I think Clara should too, at least for the short options.

**Comment by philsquared** [comment]
Another thing I've had in mind - just not got around to it yet.

**Comment by philsquared** [comment]
This is in now (0.0.2.0). Currently always available. Might make it configurable...

**Comment by philsquared** [comment]
Still in v1.0 - only when building for Windows. I'm going to close this.
